mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${MYSQL_ANALYZE_USER}@'%' IDENTIFIED BY '${MYSQL_ANALYZE_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT SELECT ON ${MYSQL_DATABASE}.* TO ${MYSQL_ANALYZE_USER}@'%';"
