mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"CREATE USER ${MYSQL_BACKUP_USER}@'%' IDENTIFIED BY '${MYSQL_BACKUP_PASSWORD}';"
mysql -u root -p${MYSQL_ROOT_PASSWORD} -e"GRANT SELECT ON ${MYSQL_DATABASE}.* TO ${MYSQL_BACKUP_USER}@'%';"
